name: check

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install -d

      - name: Lint code
        run: pipenv run lint

      - name: Run unit tests
        run: pipenv run test-unit

      - name: Use fake git credentials
        run: |
          git config --global user.email "example@xyz.com"
          git config --global user.name "Quentin Beck"

      - name: Run functional tests
        run: pipenv run test-func
