name: check

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        description: 'Operating system'
        required: true
        type: string

jobs:
  check:
    runs-on: ${{ inputs.os }}

    steps:
      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install -d

      - name: Install internal packages
        run: pipenv run setup

      - name: Lint code
        run: pipenv run lint

      - name: Run unit tests
        run: pipenv run test-unit

      - name: Use fake git credentials
        run: |
          git config --global user.email "example@xyz.com"
          git config --global user.name "Quentin Beck"

      - name: Run smoke tests
        run: pipenv run test-smoke

      - name: Run functional tests
        run: pipenv run test-func
