name: check-on-push

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  check:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, windows-latest]

    uses: ./.github/workflows/check.yml
    with:
      os: ${{ matrix.os }}
