name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: install -d

      - name: Lint code
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run lint

      - name: Run tests
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: run test
