name: Check New Commits

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install pipenv
        uses: pip install pipenv

      - name: Install dependencies
        run: pipenv install -d

      - name: Lint code
        run: pipenv run lint

      - name: Run unit tests
        run: pipenv run test-unit

      - name: Run functional tests
        run: pipenv run test-func
