name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Get version from tag
        id: tag_name
        run: |
          echo ::set-output name=current_version::${GITHUB_REF#refs/tags/v}
        shell: bash

      - name: Set up java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install pipenv
        run: pip install pipenv

      - name: Install dependencies
        run: pipenv install -d

      - name: Lint code
        run: pipenv run lint

      - name: Run unit tests
        run: pipenv run test-unit

      - name: Use fake git credentials
        run: |
          git config --global user.email "example@xyz.com"
          git config --global user.name "Quentin Beck"

      - name: Run functional tests
        run: pipenv run test-func

      - name: Build distribution
        run: pipenv run build

      - name: Get changelog notes
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ steps.tag_name.outputs.current_version }}
          path: ./CHANGELOG.md

      - name: Publish release to PyPi
        run: pipenv run publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}

      - name: Publish release to GitHub
        uses: actions/create-release@v1.10
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ${{ steps.changelog_reader.outputs.changes }}
